In [ ]:
# Imports da lib
import numpy as np
from sklearn import datasets

# Função de ativação
def sigmoid(soma):
    return 1 / (1 + np.exp(-soma))

def sigmoidDerivada(sig):
  return sig*(1-sig)

# Load dataset
base = datasets.load_breast_cancer()
base.data

In [ ]:
base.feature_names

In [ ]:
base.target

In [ ]:
base.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
# Entradas das informações da tabela verdade
entradas = base.data

# Valores desejados
ValoresSaidas = base.target

saidas = ValoresSaidas.reshape(-1, 1)


entradas.shape
pesos0 = 2*np.random.random((30, 3)) - 1
print(f"Pesos da camada de entrada escondida {pesos0} \n")

pesos1 = 2*np.random.random((3, 1)) - 1
print(f"Pesos da camada de entrada escondida para saida {pesos1} \n")

epocas = 1000
taxaAprendizagem = 0.3
momentos = 1

for j in range(epocas):
  camadaEntrada = entradas
  somaSinapse0 = np.dot(camadaEntrada, pesos0)
  camadaOculta = sigmoid(somaSinapse0)
  somaSinapse1 = np.dot(camadaOculta, pesos1)
  camadasaida = sigmoid(somaSinapse1)
  erroCamadaSaida = saidas - camadasaida
  mediaAbsoluta = np.mean(np.abs(erroCamadaSaida))
  print(f'Erro: {str(mediaAbsoluta)}')

  derivadaSaida = sigmoidDerivada(camadasaida)
  deltaSaida = erroCamadaSaida * derivadaSaida

  pesos1Transposta = pesos1.T
  deltaSaidaXPeso = deltaSaida.dot(pesos1Transposta)

  deltaCamadaOculta = deltaSaidaXPeso * sigmoidDerivada(camadaOculta)

  camadaOcultaTransposta = camadaOculta.T
  pesosNovo1 = camadaOcultaTransposta.dot(deltaSaida)
  pesos1 = (pesos1 * momentos) + (pesosNovo1 * taxaAprendizagem)

  camadaEntradaTransposta = camadaEntrada.T
  pesosNovo0 = camadaEntradaTransposta.dot(deltaCamadaOculta)
  pesos0 = (pesos0 * momentos) + (pesosNovo0 * taxaAprendizagem)

In [ ]:
print(f"Resultado da camada entrada para camada oculta: {somaSinapse0}")

print(f"Resultado da função de ativação sigmoid para a camada oculta: {camadaOculta}")



Resultado da camada entrada para camada oculta: [[ 1716.27258919 -2028.52398996 -1595.80731038]
 [ 1779.97899748 -2125.36849471 -1638.45935492]
 [ 1566.77577366 -1843.39948974 -1431.12897613]
 ...
 [ 1104.63398018 -1230.27036501  -965.89559733]
 [ 1704.62278345 -1951.45751311 -1535.14791139]
 [  309.67294337  -267.07263232  -232.73151364]]
Resultado da função de ativação sigmoid para a camada oculta: [[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 0.00000000e+000]
 ...
 [1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 1.02761283e-116 8.43311186e-102]]
