In [ ]:
import numpy as np
import math

In [ ]:
# Função de ativação (Sigmoid)
# -------------------------------
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Dados de entrada (XOR)
# -------------------------------
entradas = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

saidas = np.array([
    [0],
    [1],
    [1],
    [0]
])

print("\nEntradas:")
print(entradas)
print("\nSaídas esperadas:")
print(saidas)

# Pesos da rede
# -------------------------------

# Camada de entrada → camada oculta (2 entradas x 3 neurônios)
peso0 = np.array([
    [-0.424, -0.740, 0.961],
    [0.350, -0.577, 0.469]
])

# Camada oculta → camada de saída (3 neurônios x 1 saída)
peso1 = np.array([
    [-0.017],
    [-0.893],
    [-0.148]
])

print("\nPesos entrada → camada oculta:")
print(peso0)

print("\nPesos camada oculta → saída:")
print(peso1)

# Treinamento
# -------------------------------
epocas = 100
for epoca in range(epocas):

    # Camada de entrada
    camadaEntrada = entradas
    # Soma das sinapses camada oculta
    somaSinapse0 = np.dot(camadaEntrada, peso0)
    # Ativação camada oculta
    camadaOculta = sigmoid(somaSinapse0)
    # Soma das sinapses camada de saída
    somaSinapse1 = np.dot(camadaOculta, peso1)
    # Ativação camada de saída
    camadaSaida = sigmoid(somaSinapse1)
    # Cálculo do erro
    erroCamadaSaida = saidas - camadaSaida

    # Média absoluta do erro
    mediaAbsoluta = np.mean(np.abs(erroCamadaSaida))
    print(f"Época {epoca} | Erro médio: {mediaAbsoluta:.6f}")


# Resultados finais
# -------------------------------

print("\n==============================")
print("RESULTADOS FINAIS DA REDE")
print("==============================")

print("\nSoma das sinapses - camada oculta:")
print(somaSinapse0)

print("\nAtivação da camada oculta (sigmoid):")
print(camadaOculta)

print("\nSoma das sinapses - camada de saída:")
print(somaSinapse1)

print("\nSaída da rede após sigmoid:")
print(camadaSaida)

print("\nErro da camada de saída:")
print(erroCamadaSaida)

print("\nMédia absoluta do erro final:")
print(mediaAbsoluta)


Entradas:
[[0 0]
 [1 0]
 [0 1]
 [1 1]]

Saídas esperadas:
[[0]
 [1]
 [1]
 [0]]

Pesos entrada → camada oculta:
[[-0.424 -0.74   0.961]
 [ 0.35  -0.577  0.469]]

Pesos camada oculta → saída:
[[-0.017]
 [-0.893]
 [-0.148]]
Época 0 | Erro médio: 0.498886
Época 1 | Erro médio: 0.498886
Época 2 | Erro médio: 0.498886
Época 3 | Erro médio: 0.498886
Época 4 | Erro médio: 0.498886
Época 5 | Erro médio: 0.498886
Época 6 | Erro médio: 0.498886
Época 7 | Erro médio: 0.498886
Época 8 | Erro médio: 0.498886
Época 9 | Erro médio: 0.498886
Época 10 | Erro médio: 0.498886
Época 11 | Erro médio: 0.498886
Época 12 | Erro médio: 0.498886
Época 13 | Erro médio: 0.498886
Época 14 | Erro médio: 0.498886
Época 15 | Erro médio: 0.498886
Época 16 | Erro médio: 0.498886
Época 17 | Erro médio: 0.498886
Época 18 | Erro médio: 0.498886
Época 19 | Erro médio: 0.498886
Época 20 | Erro médio: 0.498886
Época 21 | Erro médio: 0.498886
Época 22 | Erro médio: 0.498886
Época 23 | Erro médio: 0.498886
Época 24 | Erro médi

In [ ]:
#criando a função de sigmoid
def sigmoid(soma):
  return 1/(1+np.exp(-soma))

In [ ]:
#criando a derivada da função
def sigmoidDerivada(sig):
  return sig*(1-sig)

In [ ]:
a = sigmoid(0.5)
print(a)

0.6224593312018546


In [ ]:
b = sigmoidDerivada(a)
print(b)

0.2350037122015945


In [ ]:
#entrada das informações da tabela
entradas = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [ ]:
#valores desejados
saidas = np.array([[0],[1],[1],[0]])

In [ ]:
peso0 = np.array([[-0.424,-0.740,-0.961],
                  [-0.358,-0.577,-0.469]])

print("pesos da camada oculta")
print(peso0)

pesos da camada oculta
[[-0.424 -0.74  -0.961]
 [-0.358 -0.577 -0.469]]


In [ ]:
pesos1 = np.array([[-0.017],[-0.893],[0.148]])
print("pesos da camda de saida")
print(pesos1)

pesos da camda de saida
[[-0.017]
 [-0.893]
 [ 0.148]]


In [ ]:
epocas = 100


In [ ]:
for j in range(epocas):
  camadaEntrada = entradas

  somaSinapse0 = np.dot(camadaEntrada,peso0)
  camadaOculta = sigmoid(somaSinapse0)

  somaSinapse1 = np.dot(camadaOculta,pesos1)
  camadaSaida = sigmoid(somaSinapse1)

  erroCamadaSaida = saidas - camadaSaida
  mediaAbsoluta = np.mean(np.abs(erroCamadaSaida))
